version: "3"
services:

  mongodb:
    image: mongo:4.2.8
    container_name: "mongodb"
    volumes:
      - ./mongodb/data/db:/data/db
    ports:
      - "27017:27017"


  jupyter:
    build: notebooks
    container_name: "notebook"
    volumes:
      - "./:/home/jovyan/NLP"
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    links:
      - mongodb
    depends_on:
      - mongodb

